- name: Gather the package facts
  package_facts:
    manager: auto

- name: Creates directory
  ansible.builtin.file:
    path: "{{ tools_path }}"
    state: directory

- name: Copy main script
  ansible.builtin.copy:
    src: ../monitor.py
    dest: "{{ tools_path }}/monitor.py"
    force: true

- name: Copy main env
  ansible.builtin.copy:
    src: ../.env
    dest: "{{ tools_path }}/.env"
    force: true

- name: Copy main requirements
  ansible.builtin.copy:
    src: ../requirements.txt
    dest: "{{ tools_path }}/requirements.txt"
    force: true

- pip:
     requirements: "{{ tools_path }}/requirements.txt"
     virtualenv: "{{ tools_path }}/venv"
     virtualenv_command: /usr/bin/python3 -m venv

- name: Template a systemd to /etc/systemd/system
  ansible.builtin.template:
    src: templates/systemd_monitoring_service.j2
    dest: "{{ tools_path }}/{{ systemd_service_name }}.service"


- name: Move file
  command: "mv {{ tools_path }}/{{ systemd_service_name }}.service /etc/systemd/system/{{ systemd_service_name }}.service"
  become_user: root
  become: true

- name: Restart service monitoring
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: "{{ systemd_service_name }}"
  enabled: true
  become: true
  become_user: root